//
// Created by Radu Ursu on 14/11/23.
//

#ifndef LABORATORIODIPROGRAMMAZIONE_SHOPPINGITEM_H
#define LABORATORIODIPROGRAMMAZIONE_SHOPPINGITEM_H


class ShoppingItem {

};


#endif //LABORATORIODIPROGRAMMAZIONE_SHOPPINGITEM_H
